// File generated by FlutterFire CLI & manually configured.
// Project: brahma-journal-nhdat
// Generated: 2026-08-04

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios; // Uses same config as iOS
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ✅ Web App (from .env — same as website)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXXQRlFPZFpeDkLCal53fT7qI5eLU2gww',
    appId: '1:440787316408:web:4f5edcadc3469db577ce4d',
    messagingSenderId: '440787316408',
    projectId: 'brahma-journal-nhdat',
    authDomain: 'brahma-journal-nhdat.firebaseapp.com',
    storageBucket: 'brahma-journal-nhdat.firebasestorage.app',
    measurementId: 'G-Y5XWGVB3SC',
  );

  // ✅ Android App (registered via flutterfire configure)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF_dSt3E4TWndADhDVksyS0qFauI-bhuk',
    appId: '1:440787316408:android:38e64b73850e55b977ce4d',
    messagingSenderId: '440787316408',
    projectId: 'brahma-journal-nhdat',
    storageBucket: 'brahma-journal-nhdat.firebasestorage.app',
  );

  // ✅ iOS App (registered via flutterfire configure)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXXQRlFPZFpeDkLCal53fT7qI5eLU2gww',
    appId: '1:440787316408:ios:df0bf97bd474bda477ce4d',
    messagingSenderId: '440787316408',
    projectId: 'brahma-journal-nhdat',
    storageBucket: 'brahma-journal-nhdat.firebasestorage.app',
    iosBundleId: 'com.brahma.brahmaApp',
  );
}
